[package]
name = "frd_lisp"
version = "0.1.0"
authors = ["Fran Guijarro <franleplant@gmail.com>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
lalrpop = { version = "0.19.0", features = ["lexer"] }

[dependencies]
lalrpop-util = "0.19.0"
regex = "1"
log = "0.4.11"
env_logger = "0.7.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = "0.3"
