[package]
name = "lisp2018-lalrpop"
version = "0.1.0"
authors = ["Fran Guijarro <franleplant@gmail.com>"]

[build-dependencies] # <-- We added this and everything after!
lalrpop = "0.16.2"

[dependencies]
lalrpop-util = "0.16.2"
regex = "0.2.1"
log = "0.4.6"
env_logger = "*"

