name: ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run formatter
      run: cargo fmt -- --check
    - name: Run clippy (linter)
      run: cargo clippy -- -Dwarnings
